### PR TITLE
Create FizzBuzz.java

### PR DESCRIPTION
**Pull request by TSG405**
Please accept my PR for hactoberfest 2022 @Mystery-2-Dev :)

### CODE REVIEW

**Comment by TSG405** [comment]
Why is this repo not participating?

**Comment by Mystery-2-Dev** [comment]
This repo is participating

**Comment by TSG405** [comment]
Yup okay, might be a glitch in website. Anyways thanks :) Any more valid repo that you can advice? Need 1 or 2

**Comment by Mystery-2-Dev** [comment]
Ya sure

**Pull request merged**
